# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home"
  weight = 10

[[main]]
  name = "Curriculum"
  url = "/curriculum/overview"
  weight = 20

[[main]]
  name = "Introduction"
  url = "/curriculum/introduction"
  parent = "Curriculum"
  weight = 21

[[main]]
  name = "Complex numbers and phasors"
  url = "/curriculum/complex"
  parent = "Curriculum"
  weight = 22

[[main]]
  name = "Spectrum and Fourier series"
  url = "/curriculum/spectrum"
  parent = "Curriculum"
  weight = 23

[[main]]
  name = "Sampling and aliasing"
  url = "/curriculum/sampling"
  parent = "Curriculum"
  weight = 24

[[main]]
  name = "FIR filters"
  url = "/curriculum/fir"
  parent = "Curriculum"
  weight = 25

[[main]]
  name = "Frequency response"
  url = "/curriculum/frequency"
  parent = "Curriculum"
  weight = 26

[[main]]
  name = "Courses"
  weight = 40

[[main]]
  name = "Signal processing basics"
  url = "/courses/Signals1"
  parent = "Courses"
  weight = 41

[[main]]
  name = "DSP fundamentals"
  url = "/courses/Signals2"
  parent = "Courses"
  weight = 42

[[main]]
  name = "Signal analysis and estimation"
  url = "/courses/Signals3"
  parent = "Courses"
  weight = 43

[[main]]
  name = "Adaptive array signal processing"
  url = "/courses/AASP"
  parent = "Courses"
  weight = 44

[[main]]
  name = "Adaptive information processing"
  url = "/courses/AIP"
  parent = "Courses"
  weight = 45


[[main]]
  name = "Projects"
  url = "#projects"
  weight = 60

[[main]]
  name = "Tutorials"
  url = "/tutorial/"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
