# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home"
  weight = 10

[[main]]
  name = "Curriculum"
  url = "/curriculum/"
  weight = 20

[[main]]
  name = "Basic math"
  url = "/curriculum"
  parent = "Curriculum"
  weight = 1

[[main]]
  name = "Fourier transform"
  url = "/curriculum/fourier"
  parent = "Curriculum"
  weight = 2

[[main]]
  name = "Sampling and aliasing"
  url = "/curriculum/sampling"
  parent = "Curriculum"
  weight = 3

[[main]]
  name = "Spectral estimation"
  url = "/curriculum/spectralestimation"
  parent = "Curriculum"
  weight = 4

[[main]]
  name = "Adaptive processing"
  url = "/curriculum/adaptive"
  parent = "Curriculum"
  weight = 5

[[main]]
  name = "Spatial filtering"
  url = "/curriculum/spatial"
  parent = "Curriculum"
  weight = 6

[[main]]
  name = "Courses"
  weight = 30

[[main]]
  name = "Signal processing basics"
  url = "/courses/Signals1"
  parent = "Courses"
  weight = 1

[[main]]
  name = "DSP fundamentals"
  url = "/courses/Signals2"
  parent = "Courses"
  weight = 2

[[main]]
  name = "Signal analysis and estimation"
  url = "/courses/Signals3"
  parent = "Courses"
  weight = 3

[[main]]
  name = "Adaptive array signal processing"
  url = "/courses/AASP"
  parent = "Courses"
  weight = 4

[[main]]
  name = "Adaptive information processing"
  url = "/courses/AIP"
  parent = "Courses"
  weight = 5


[[main]]
  name = "Projects"
  url = "#projects"
  weight = 40

[[main]]
  name = "Tutorials"
  url = "/tutorial/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
