# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home"
  weight = 10

[[main]]
  name = "SPS info"
  url = "/info/main"
  weight = 11

  [[main]]
  name = "General info"
  url = "/info/main"
  weight = 12
  parent = "SPS info"


  [[main]]
  name = "Bachelor program"
  url = "/info/bachelor_main"
  weight = 13
  parent = "SPS info"

  [[main]]
  name = "Master program"
  url = "/info/master_main"
  weight = 14
  parent = "SPS info"

[[main]]
  name = "Study material"
  url = "/disciplines/overview"
  weight = 20


###################### MATHEMATICAL BACKGROUND #################################
[[main]]
  name = "Mathematical background"
  url = "/disciplines/mathematicalbackground/mathematicalbackground_main"
  parent = "Study material"
  weight = 22



######################## CONTINUOUS SIGNAL PROCESSING ##############################
[[main]]
  name = "Basics of continuous-time signals and systems"
  url = "/disciplines/continuous/continuoussignalprocessing_main"
  parent = "Study material"
  weight = 23


  ######################## DISCRETE SIGNAL PROCESSING ##############################
  [[main]]
    name = "Discrete-time signal processing basics"
    url = "/disciplines/discrete/discretesignalprocessing_main"
    parent = "Study material"
    weight = 24


######################## STATISTICAL SIGNAL PROCESSING ##############################
[[main]]
  name = "Statistical signal processing"
  url = "/disciplines/statistical/statisticalsignalprocessing_main"
  parent = "Study material"
  weight = 25



######################## MULTIDIMENSIONAL SIGNAL PROCESSING ##############################
# [[main]]
#   name = "Multidimensional signal processing (to be added)"
#   url = "/disciplines/multidimensional/multidimensionalsignalprocessing_main"
#   parent = "Study material"
#   weight = 26



######################## OPTIMAL AND ADAPTIVE SIGNAL PROCESSING ##############################
[[main]]
  name = "Optimal and adaptive signal processing (to be added)"
  url = "/disciplines/optimalandadaptive/optimalandadaptivesignalprocessing_main"
  parent = "Study material"
  weight = 27



######################## SENSOR ARRAY AND MULTICHANNEL SIGNAL PROCESSING ##############################
[[main]]
  name = "Sensor array and multichannel signal processing (to be added)"
  url = "/disciplines/sensorarrayandmultichannel/sensorarrayandmultichannelsignalprocessing_main"
  parent = "Study material"
  weight = 28


######################## MACHINE LEARNING ##############################
[[main]]
  name = "Machine learning (to be added)"
  url = "/disciplines/machinelearning/machinelearning_main"
  parent = "Study material"
  weight = 29



######################## INFORMATION AND COMMUNICATION THEORY ##############################
[[main]]
  name = "Information and communication theory (to be added)"
  url = "/disciplines/information/informationandcommunication_main"
  parent = "Study material"
  weight = 30



############################### Courses #################################
[[main]]
  name = "Courses"
  url = "/courses/overview"
  weight = 40

[[main]]
  name = "5ESE0 - Signal processing basics"
  url = "/courses/5ese0/5ese0"
  parent = "Courses"
  weight = 41

[[main]]
  name = "5CTA0 - Statistical signal processing"
  url = "/courses/5cta0/5cta0"
  parent = "Courses"
  weight = 42


############################## CONTACT ##################################

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
