# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home"
  weight = 10

[[main]]
  name = "Curriculum"
  url = "/curriculum/overview"
  weight = 20

# [[main]]
#   name = "Introduction"
#   url = "/curriculum/introduction"
#   parent = "Curriculum"
#   weight = 21

###################### MATHEMATICAL BACKGROUND #################################
[[main]]
  name = "Mathematical background"
  url = "/curriculum/mathematicalbackground/mathematicalbackground_main"
  parent = "Curriculum"
  weight = 22



######################## CONTINUOUS SIGNAL PROCESSING ##############################
[[main]]
  name = "Continuous signal processing basics"
  url = "/curriculum/continuous/continuoussignalprocessing_main"
  parent = "Curriculum"
  weight = 23


  ######################## DISCRETE SIGNAL PROCESSING ##############################
  [[main]]
    name = "Discrete-time signal processing basics"
    url = "/curriculum/discrete/discretesignalprocessing_main"
    parent = "Curriculum"
    weight = 24


######################## STATISTICAL SIGNAL PROCESSING ##############################
[[main]]
  name = "Statistical signal processing"
  url = "/curriculum/statistical/statisticalsignalprocessing_main"
  parent = "Curriculum"
  weight = 25



######################## MULTIDIMENSIONAL SIGNAL PROCESSING ##############################
[[main]]
  name = "Multidimensional signal processing"
  url = "/curriculum/multidimensional/multidimensionalsignalprocessing_main"
  parent = "Curriculum"
  weight = 26



######################## OPTIMAL AND ADAPTIVE SIGNAL PROCESSING ##############################
[[main]]
  name = "Optimal and adaptive signal processing"
  url = "/curriculum/optimalandadaptive/optimalandadaptivesignalprocessing_main"
  parent = "Curriculum"
  weight = 27



######################## SENSOR ARRAY AND MULTICHANNEL SIGNAL PROCESSING ##############################
[[main]]
  name = "Sensor array and multichannel signal processing"
  url = "/curriculum/sensorarrayandmultichannel/sensorarrayandmultichannelsignalprocessing_main"
  parent = "Curriculum"
  weight = 28


######################## MACHINE LEARNING ##############################
[[main]]
  name = "Machine learning"
  url = "/curriculum/machinelearning/machinelearning_main"
  parent = "Curriculum"
  weight = 29



######################## INFORMATION AND COMMUNICATION THEORY ##############################
[[main]]
  name = "Information and communication theory"
  url = "/curriculum/information/informationandcommunication_main"
  parent = "Curriculum"
  weight = 30




############################## CONTACT ##################################

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
